db.social.drop()
db.social.insertMany([
  {
    "ID": 1,
    "Nombre": "Guntar",
    "Apellido1": "Iredale",
    "Apellido2": "Antonich",
    "FecNac": new Date("1984-03-03T19:53:52.000Z"),
    "Género": "Female",
    "Nacionalidad": "China",
    "Correo": "gantonich0@usnews.com",
    "Validado": true,
    "Usuario": "gantonich0",
    "Seguidores": 50454
  }, {
    "ID": 2,
    "Nombre": "Gloriane",
    "Apellido1": "Jorger",
    "Apellido2": "Rookesby",
    "FecNac": new Date("1979-02-20T09:46:05.000Z"),
    "Género": "Female",
    "Nacionalidad": "Finland",
    "Correo": "grookesby1@sbwire.com",
    "Validado": false,
    "Usuario": "grookesby1",
    "Seguidores": 91706
  }, {
    "ID": 3,
    "Nombre": "Dory",
    "Apellido1": "Nassi",
    "Apellido2": "Finch",
    "FecNac": new Date("1970-08-12T17:05:28.000Z"),
    "Género": "Female",
    "Nacionalidad": "Zambia",
    "Correo": "dfinch2@com.com",
    "Validado": true,
    "Usuario": "dfinch2",
    "Seguidores": 7346
  }, {
    "ID": 4,
    "Nombre": "Shaine",
    "Apellido1": "Chatelot",
    "Apellido2": "Hubach",
    "FecNac": new Date("1979-04-13T09:05:10.000Z"),
    "Género": "Female",
    "Nacionalidad": "United States",
    "Correo": "shubach3@hexun.com",
    "Validado": true,
    "Usuario": "shubach3",
    "Seguidores": 14822
  }, {
    "ID": 5,
    "Nombre": "Adora",
    "Apellido1": "Grimster",
    "Apellido2": "Swinburn",
    "FecNac": new Date("1975-11-06T02:19:22.000Z"),
    "Género": "Male",
    "Nacionalidad": "South Korea",
    "Correo": "aswinburn4@cpanel.net",
    "Validado": false,
    "Usuario": "aswinburn4",
    "Seguidores": 12027
  }, {
    "ID": 6,
    "Nombre": "Britta",
    "Apellido1": "Battany",
    "Apellido2": "Youdell",
    "FecNac": new Date("1987-03-15T07:53:00.000Z"),
    "Género": "Female",
    "Nacionalidad": "Philippines",
    "Correo": "byoudell5@dell.com",
    "Validado": false,
    "Usuario": "byoudell5",
    "Seguidores": 54672
  }, {
    "ID": 7,
    "Nombre": "Baudoin",
    "Apellido1": "Donisthorpe",
    "Apellido2": "Briars",
    "FecNac": new Date("1978-08-19T09:57:28.000Z"),
    "Género": "Female",
    "Nacionalidad": "Colombia",
    "Correo": "bbriars6@163.com",
    "Validado": false,
    "Usuario": "bbriars6",
    "Seguidores": 38742
  }, {
    "ID": 8,
    "Nombre": "Earl",
    "Apellido1": "Salan",
    "Apellido2": "O'Loughlin",
    "FecNac": new Date("1983-09-30T17:53:06.000Z"),
    "Género": "Female",
    "Nacionalidad": "Russia",
    "Correo": "eoloughlin7@sbwire.com",
    "Validado": true,
    "Usuario": "eoloughlin7",
    "Seguidores": 13362
  }, {
    "ID": 9,
    "Nombre": "Wilbur",
    "Apellido1": "Mepham",
    "Apellido2": "Kilgallen",
    "FecNac": new Date("1991-07-23T08:18:31.000Z"),
    "Género": "Female",
    "Nacionalidad": "China",
    "Correo": "wkilgallen8@google.nl",
    "Validado": false,
    "Usuario": "wkilgallen8",
    "Seguidores": 91538
  }, {
    "ID": 10,
    "Nombre": "Clark",
    "Apellido1": "Ainger",
    "Apellido2": "Crummie",
    "FecNac": new Date("1999-07-24T11:43:51.000Z"),
    "Género": "Female",
    "Nacionalidad": "China",
    "Correo": "ccrummie9@trellian.com",
    "Validado": true,
    "Usuario": "ccrummie9",
    "Seguidores": 12924
  }, {
    "ID": 11,
    "Nombre": "Simmonds",
    "Apellido1": "Oris",
    "Apellido2": "McCosh",
    "FecNac": new Date("1970-06-06T13:00:00.000Z"),
    "Género": "Male",
    "Nacionalidad": "Thailand",
    "Correo": "smccosha@huffingtonpost.com",
    "Validado": false,
    "Usuario": "smccosha",
    "Seguidores": 12440
  }, {
    "ID": 12,
    "Nombre": "Hayden",
    "Apellido1": "Dunridge",
    "Apellido2": "Sweeting",
    "FecNac": new Date("1984-10-08T12:07:37.000Z"),
    "Género": "Female",
    "Nacionalidad": "Honduras",
    "Correo": "hsweetingb@t.co",
    "Validado": false,
    "Usuario": "hsweetingb",
    "Seguidores": 70591
  }, {
    "ID": 13,
    "Nombre": "Theadora",
    "Apellido1": "Pancoust",
    "Apellido2": "Buckleigh",
    "FecNac": new Date("1971-06-15T20:01:50.000Z"),
    "Género": "Female",
    "Nacionalidad": "Portugal",
    "Correo": "tbuckleighc@wired.com",
    "Validado": false,
    "Usuario": "tbuckleighc",
    "Seguidores": 30100
  }, {
    "ID": 14,
    "Nombre": "Nike",
    "Apellido1": "Gervaise",
    "Apellido2": "Bridgnell",
    "FecNac": new Date("1970-07-29T14:52:48.000Z"),
    "Género": "Male",
    "Nacionalidad": "Latvia",
    "Correo": "nbridgnelld@icio.us",
    "Validado": true,
    "Usuario": "nbridgnelld",
    "Seguidores": 20345
  }, {
    "ID": 15,
    "Nombre": "Westley",
    "Apellido1": "Kyle",
    "Apellido2": "Castiello",
    "FecNac": new Date("1977-11-01T07:05:13.000Z"),
    "Género": "Male",
    "Nacionalidad": "China",
    "Correo": "wcastielloe@odnoklassniki.ru",
    "Validado": true,
    "Usuario": "wcastielloe",
    "Seguidores": 59986
  }, {
    "ID": 16,
    "Nombre": "Eba",
    "Apellido1": "Maudsley",
    "Apellido2": "Rendall",
    "FecNac": new Date("1980-06-11T15:17:06.000Z"),
    "Género": "Male",
    "Nacionalidad": "China",
    "Correo": "erendallf@cargocollective.com",
    "Validado": true,
    "Usuario": "erendallf",
    "Seguidores": 68076
  }, {
    "ID": 17,
    "Nombre": "Orton",
    "Apellido1": "Zmitruk",
    "Apellido2": "Matyas",
    "FecNac": new Date("1985-06-25T12:39:49.000Z"),
    "Género": "Female",
    "Nacionalidad": "France",
    "Correo": "omatyasg@timesonline.co.uk",
    "Validado": false,
    "Usuario": "omatyasg",
    "Seguidores": 8338
  }, {
    "ID": 18,
    "Nombre": "Britt",
    "Apellido1": "Maseres",
    "Apellido2": "Spadollini",
    "FecNac": new Date("1983-10-14T19:33:23.000Z"),
    "Género": "Female",
    "Nacionalidad": "Yemen",
    "Correo": "bspadollinih@usnews.com",
    "Validado": true,
    "Usuario": "bspadollinih",
    "Seguidores": 2751
  }, {
    "ID": 19,
    "Nombre": "Robbin",
    "Apellido1": "Kyncl",
    "Apellido2": "Gooms",
    "FecNac": new Date("1974-04-07T08:54:50.000Z"),
    "Género": "Female",
    "Nacionalidad": "Sweden",
    "Correo": "rgoomsi@shareasale.com",
    "Validado": false,
    "Usuario": "rgoomsi",
    "Seguidores": 4982
  }, {
    "ID": 20,
    "Nombre": "Elnore",
    "Apellido1": "Mignot",
    "Apellido2": "Kerfoot",
    "FecNac": new Date("1979-09-22T03:10:53.000Z"),
    "Género": "Male",
    "Nacionalidad": "France",
    "Correo": "ekerfootj@sitemeter.com",
    "Validado": false,
    "Usuario": "ekerfootj",
    "Seguidores": 29215
  }, {
    "ID": 21,
    "Nombre": "Freemon",
    "Apellido1": "Cushe",
    "Apellido2": "Rubi",
    "FecNac": new Date("1998-10-06T05:17:25.000Z"),
    "Género": "Female",
    "Nacionalidad": "Sweden",
    "Correo": "frubik@rakuten.co.jp",
    "Validado": false,
    "Usuario": "frubik",
    "Seguidores": 91060
  }, {
    "ID": 22,
    "Nombre": "Goddard",
    "Apellido1": "Rounsivall",
    "Apellido2": "Fluck",
    "FecNac": new Date("1989-10-12T01:20:29.000Z"),
    "Género": "Female",
    "Nacionalidad": "Pakistan",
    "Correo": "gfluckl@twitpic.com",
    "Validado": true,
    "Usuario": "gfluckl",
    "Seguidores": 79137
  }, {
    "ID": 23,
    "Nombre": "Nolie",
    "Apellido1": "De Giorgio",
    "Apellido2": "Wyke",
    "FecNac": new Date("1971-03-21T21:41:20.000Z"),
    "Género": "Male",
    "Nacionalidad": "China",
    "Correo": "nwykem@vistaprint.com",
    "Validado": true,
    "Usuario": "nwykem",
    "Seguidores": 78136
  }, {
    "ID": 24,
    "Nombre": "Barbara",
    "Apellido1": "Lovart",
    "Apellido2": "Caisley",
    "FecNac": new Date("1989-11-30T00:43:55.000Z"),
    "Género": "Male",
    "Nacionalidad": "Haiti",
    "Correo": "bcaisleyn@dedecms.com",
    "Validado": false,
    "Usuario": "bcaisleyn",
    "Seguidores": 81313
  }, {
    "ID": 25,
    "Nombre": "Lesya",
    "Apellido1": "Carnegy",
    "Apellido2": "Mourbey",
    "FecNac": new Date("1986-12-10T09:35:47.000Z"),
    "Género": "Female",
    "Nacionalidad": "China",
    "Correo": "lmourbeyo@cnn.com",
    "Validado": true,
    "Usuario": "lmourbeyo",
    "Seguidores": 79724
  }, {
    "ID": 26,
    "Nombre": "Cleopatra",
    "Apellido1": "Cunningham",
    "Apellido2": "Jakaway",
    "FecNac": new Date("1980-03-25T18:53:20.000Z"),
    "Género": "Male",
    "Nacionalidad": "Philippines",
    "Correo": "cjakawayp@people.com.cn",
    "Validado": true,
    "Usuario": "cjakawayp",
    "Seguidores": 11292
  }, {
    "ID": 27,
    "Nombre": "Marilee",
    "Apellido1": "Crisp",
    "Apellido2": "Skilling",
    "FecNac": new Date("1994-03-08T16:54:58.000Z"),
    "Género": "Male",
    "Nacionalidad": "Namibia",
    "Correo": "mskillingq@mapquest.com",
    "Validado": true,
    "Usuario": "mskillingq",
    "Seguidores": 27801
  }, {
    "ID": 28,
    "Nombre": "Jorge",
    "Apellido1": "Baddoe",
    "Apellido2": "Riseley",
    "FecNac": new Date("1988-04-01T15:57:42.000Z"),
    "Género": "Female",
    "Nacionalidad": "China",
    "Correo": "jriseleyr@opensource.org",
    "Validado": false,
    "Usuario": "jriseleyr",
    "Seguidores": 85225
  }, {
    "ID": 29,
    "Nombre": "Padriac",
    "Apellido1": "Mantz",
    "Apellido2": "Morpeth",
    "FecNac": new Date("1992-05-06T03:22:12.000Z"),
    "Género": "Male",
    "Nacionalidad": "Kazakhstan",
    "Correo": "pmorpeths@accuweather.com",
    "Validado": true,
    "Usuario": "pmorpeths",
    "Seguidores": 87351
  }, {
    "ID": 30,
    "Nombre": "Zarla",
    "Apellido1": "Brady",
    "Apellido2": "Kenen",
    "FecNac": new Date("1995-01-20T12:48:41.000Z"),
    "Género": "Male",
    "Nacionalidad": "Jordan",
    "Correo": "zkenent@state.gov",
    "Validado": false,
    "Usuario": "zkenent",
    "Seguidores": 36358
  }, {
    "ID": 31,
    "Nombre": "Judie",
    "Apellido1": "Nossent",
    "Apellido2": "Di Biasi",
    "FecNac": new Date("1989-11-26T03:18:58.000Z"),
    "Género": "Male",
    "Nacionalidad": "Philippines",
    "Correo": "jdibiasiu@cam.ac.uk",
    "Validado": true,
    "Usuario": "jdibiasiu",
    "Seguidores": 31584
  }, {
    "ID": 32,
    "Nombre": "Lindsey",
    "Apellido1": "Blunden",
    "Apellido2": "Terbrug",
    "FecNac": new Date("1978-02-06T15:32:22.000Z"),
    "Género": "Male",
    "Nacionalidad": "Russia",
    "Correo": "lterbrugv@jimdo.com",
    "Validado": true,
    "Usuario": "lterbrugv",
    "Seguidores": 47608
  }, {
    "ID": 33,
    "Nombre": "Arabela",
    "Apellido1": "Morigan",
    "Apellido2": "Ottewill",
    "FecNac": new Date("1976-08-05T10:05:41.000Z"),
    "Género": "Male",
    "Nacionalidad": "China",
    "Correo": "aottewillw@fema.gov",
    "Validado": true,
    "Usuario": "aottewillw",
    "Seguidores": 26835
  }, {
    "ID": 34,
    "Nombre": "Constantino",
    "Apellido1": "Jepson",
    "Apellido2": "Saines",
    "FecNac": new Date("1988-12-30T10:40:22.000Z"),
    "Género": "Male",
    "Nacionalidad": "China",
    "Correo": "csainesx@patch.com",
    "Validado": false,
    "Usuario": "csainesx",
    "Seguidores": 88674
  }, {
    "ID": 35,
    "Nombre": "Dorthea",
    "Apellido1": "Szymanowski",
    "Apellido2": "Spaice",
    "FecNac": new Date("1972-02-29T17:08:37.000Z"),
    "Género": "Male",
    "Nacionalidad": "United States",
    "Correo": "dspaicey@cisco.com",
    "Validado": false,
    "Usuario": "dspaicey",
    "Seguidores": 57609
  }, {
    "ID": 36,
    "Nombre": "Paton",
    "Apellido1": "Tuma",
    "Apellido2": "Ashworth",
    "FecNac": new Date("1998-03-27T22:07:58.000Z"),
    "Género": "Male",
    "Nacionalidad": "Argentina",
    "Correo": "pashworthz@sphinn.com",
    "Validado": false,
    "Usuario": "pashworthz",
    "Seguidores": 96318
  }, {
    "ID": 37,
    "Nombre": "Joline",
    "Apellido1": "Widdicombe",
    "Apellido2": "Muschette",
    "FecNac": new Date("1991-07-23T12:32:15.000Z"),
    "Género": "Male",
    "Nacionalidad": "Morocco",
    "Correo": "jmuschette10@epa.gov",
    "Validado": false,
    "Usuario": "jmuschette10",
    "Seguidores": 27368
  }, {
    "ID": 38,
    "Nombre": "Gottfried",
    "Apellido1": "Cosens",
    "Apellido2": "Gerbi",
    "FecNac": new Date("1992-01-27T21:34:48.000Z"),
    "Género": "Female",
    "Nacionalidad": "China",
    "Correo": "ggerbi11@cmu.edu",
    "Validado": false,
    "Usuario": "ggerbi11",
    "Seguidores": 86737
  }, {
    "ID": 39,
    "Nombre": "Salomon",
    "Apellido1": "O'Scollain",
    "Apellido2": "Slaymaker",
    "FecNac": new Date("1974-07-19T09:35:47.000Z"),
    "Género": "Male",
    "Nacionalidad": "Palestinian Territory",
    "Correo": "sslaymaker12@furl.net",
    "Validado": true,
    "Usuario": "sslaymaker12",
    "Seguidores": 69753
  }, {
    "ID": 40,
    "Nombre": "Shelton",
    "Apellido1": "Trott",
    "Apellido2": "Boyfield",
    "FecNac": new Date("1988-07-23T10:50:53.000Z"),
    "Género": "Male",
    "Nacionalidad": "Ukraine",
    "Correo": "sboyfield13@smh.com.au",
    "Validado": true,
    "Usuario": "sboyfield13",
    "Seguidores": 15027
  }, {
    "ID": 41,
    "Nombre": "Libbi",
    "Apellido1": "Elstob",
    "Apellido2": "Crallan",
    "FecNac": new Date("1994-09-29T12:46:52.000Z"),
    "Género": "Female",
    "Nacionalidad": "China",
    "Correo": "lcrallan14@disqus.com",
    "Validado": false,
    "Usuario": "lcrallan14",
    "Seguidores": 70864
  }, {
    "ID": 42,
    "Nombre": "Tann",
    "Apellido1": "Paule",
    "Apellido2": "Pocknell",
    "FecNac": new Date("1971-09-14T09:35:48.000Z"),
    "Género": "Female",
    "Nacionalidad": "Indonesia",
    "Correo": "tpocknell15@comsenz.com",
    "Validado": true,
    "Usuario": "tpocknell15",
    "Seguidores": 78939
  }, {
    "ID": 43,
    "Nombre": "Noella",
    "Apellido1": "Lerigo",
    "Apellido2": "Gresly",
    "FecNac": new Date("1992-03-07T19:14:14.000Z"),
    "Género": "Female",
    "Nacionalidad": "United States",
    "Correo": "ngresly16@cargocollective.com",
    "Validado": true,
    "Usuario": "ngresly16",
    "Seguidores": 39972
  }, {
    "ID": 44,
    "Nombre": "Katherina",
    "Apellido1": "Puttergill",
    "Apellido2": "Bluett",
    "FecNac": new Date("1995-02-02T08:46:57.000Z"),
    "Género": "Male",
    "Nacionalidad": "Russia",
    "Correo": "kbluett17@msn.com",
    "Validado": false,
    "Usuario": "kbluett17",
    "Seguidores": 4795
  }, {
    "ID": 45,
    "Nombre": "Layne",
    "Apellido1": "Siuda",
    "Apellido2": "Benedetti",
    "FecNac": new Date("1987-03-22T06:29:56.000Z"),
    "Género": "Female",
    "Nacionalidad": "Tajikistan",
    "Correo": "lbenedetti18@gov.uk",
    "Validado": true,
    "Usuario": "lbenedetti18",
    "Seguidores": 55056
  }, {
    "ID": 46,
    "Nombre": "Sari",
    "Apellido1": "Rassmann",
    "Apellido2": "Tremblett",
    "FecNac": new Date("1988-08-31T18:34:56.000Z"),
    "Género": "Male",
    "Nacionalidad": "Argentina",
    "Correo": "stremblett19@wikipedia.org",
    "Validado": true,
    "Usuario": "stremblett19",
    "Seguidores": 28752
  }, {
    "ID": 47,
    "Nombre": "Tawsha",
    "Apellido1": "Ballingal",
    "Apellido2": "McGorley",
    "FecNac": new Date("1992-05-28T04:57:47.000Z"),
    "Género": "Male",
    "Nacionalidad": "France",
    "Correo": "tmcgorley1a@bravesites.com",
    "Validado": false,
    "Usuario": "tmcgorley1a",
    "Seguidores": 88357
  }, {
    "ID": 48,
    "Nombre": "Teddie",
    "Apellido1": "Hissie",
    "Apellido2": "Yancey",
    "FecNac": new Date("1975-06-17T13:51:37.000Z"),
    "Género": "Male",
    "Nacionalidad": "Argentina",
    "Correo": "tyancey1b@opensource.org",
    "Validado": false,
    "Usuario": "tyancey1b",
    "Seguidores": 84126
  }, {
    "ID": 49,
    "Nombre": "Ginny",
    "Apellido1": "Cestard",
    "Apellido2": "Keinrat",
    "FecNac": new Date("1974-06-14T15:43:37.000Z"),
    "Género": "Male",
    "Nacionalidad": "Indonesia",
    "Correo": "gkeinrat1c@fda.gov",
    "Validado": true,
    "Usuario": "gkeinrat1c",
    "Seguidores": 79029
  }, {
    "ID": 50,
    "Nombre": "Gage",
    "Apellido1": "Kitman",
    "Apellido2": "Pridham",
    "FecNac": new Date("1978-10-16T14:54:21.000Z"),
    "Género": "Male",
    "Nacionalidad": "Philippines",
    "Correo": "gpridham1d@bigcartel.com",
    "Validado": false,
    "Usuario": "gpridham1d",
    "Seguidores": 66661
  }
])
